imports:
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }

editor:
    config:
        contentsCss:
            - 'EXT:theme/Resources/Public/Css/rte.css'

        format_tags: "p;h2;h3;h4;h5;h6"

        stylesSet:

        toolbar:
            items:
                - sourceEditing
                - '|'
                - clipboard
                - removeFormat
                - '|'
                - undo
                - redo
                - '|'
                - findAndReplace
                - '|'
                - selectAll
                - '|'
                - spellchecker
                - '|'
                - textPartLanguage
                - '-'
                - bold
                - italic
                - strikethrough
                - subscript
                - superscript
                - '|'
                - bulletedList
                - numberedList
                - '|'
                - indent
                - outdent
                - '|'
                - blockQuote
                - '|'
                - link
                - '|'
                - insertTable
                - specialCharacters
                - mediaEmbed
                - '-'
                - style
                - '|'
                - heading
                - '|'
                - htmlEmbed
                - imageUpload
